import json
import os
from pathlib import Path
import sys

# Ensure convert_track can be imported
sys.path.append(str(Path(__file__).parent))
try:
    from convert_track import convert
except ImportError:
    print("[ERROR] Could not import convert from convert_track.py.")
    sys.exit(1)

def main():
    mapper_dir = Path(__file__).parent
    workspace_dir = mapper_dir.parent
    
    # Destination directories
    assets_maps_dir = workspace_dir / "telemetry-electron" / "src" / "renderer" / "src" / "assets" / "maps"
    track_maps_ts_path = workspace_dir / "telemetry-electron" / "src" / "renderer" / "src" / "lib" / "trackMaps.ts"
    
    assets_maps_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"[1/3] Scanning raw track telemetry files in: {mapper_dir.resolve()}")
    raw_files = list(mapper_dir.glob("track_*_*.json"))
    print(f"Found {len(raw_files)} raw track telemetry files.")
    
    # Track ID mapping to verify track maps
    converted_tracks = []
    
    print("\n[2/3] Converting raw telemetry files to canvas-ready maps...")
    for p in raw_files:
        try:
            # Parse track ID from filename or content
            with open(p, "r", encoding="utf-8") as f:
                raw_data = json.load(f)
            
            track_id = raw_data.get("track_id")
            if track_id is None:
                # Try to parse from filename: track_{id}_{hash}.json
                parts = p.stem.split("_")
                if len(parts) >= 2 and parts[1].isdigit():
                    track_id = int(parts[1])
                    
            if track_id is None:
                print(f"  [WARN] Skipping {p.name}: Unable to determine track ID.")
                continue
                
            print(f"  Converting Track {track_id} ({p.name}) ...")
            # Convert using convert_track logic
            result = convert(raw_data)
            
            # Save converted map to assets folder
            out_file = assets_maps_dir / f"track_{track_id}.json"
            with open(out_file, "w", encoding="utf-8") as f:
                json.dump(result, f, indent=2)
                
            print(f"    Saved: {out_file.name} ({out_file.stat().st_size} bytes)")
            converted_tracks.append(track_id)
            
        except Exception as e:
            print(f"  [ERROR] Failed to convert {p.name}: {e}")
            
    converted_tracks = sorted(list(set(converted_tracks)))
    print(f"\nSuccessfully converted and saved {len(converted_tracks)} track maps: {converted_tracks}")
    
    print(f"\n[3/3] Re-generating registry file: {track_maps_ts_path.resolve()}")
    
    # Generate the trackMaps.ts file content dynamically
    ts_imports = []
    ts_entries = []
    
    for tid in converted_tracks:
        ts_imports.append(f"import track{tid} from '../assets/maps/track_{tid}.json'")
        ts_entries.append(f"  {tid}: track{tid} as unknown as TrackMapData,")
        
    ts_imports_str = "\n".join(ts_imports)
    ts_entries_str = "\n".join(ts_entries)
    
    ts_content = f"""// This file is auto-generated by telemetry-mapper/update_app.py. Do not edit manually.
{ts_imports_str}

export interface MapTransform {{
  min_x: number
  min_z: number
  scale: number
  off_x: number
  off_z: number
}}

export interface TrackMapData {{
  track_id:       number
  track_name:     string
  circuit_name:   string
  track_length_m: number
  view_box:       {{ width: number; height: number }}
  rotation_deg:   number
  transform:      MapTransform
  sectors:        Array<{{ index: number; points: [number, number][] }}>
  drs_zones:      Array<{{
    start:        [number, number]
    end:          [number, number]
  }}>
  speed_traps:    [number, number][]
  start_finish:   [number, number] | null
}}

// Add new maps here as they are generated by convert_track.py
export const TRACK_MAPS: Record<number, TrackMapData> = {{
{ts_entries_str}
}}
"""
    
    try:
        with open(track_maps_ts_path, "w", encoding="utf-8") as f:
            f.write(ts_content)
        print(f"Successfully generated trackMaps.ts with {len(converted_tracks)} tracks!")
    except Exception as e:
        print(f"[ERROR] Failed to write trackMaps.ts: {e}")

if __name__ == "__main__":
    main()
