import type { StylesConfig } from 'react-select'

export const SELECT_MENU_ANIMATION_MS = 220

export function buildSelectStyles(isDark: boolean, { solidBg = false, controlHeight = 28, labelStyleGroupHeadings = false, menuWidth, scrollableMenu = true }: { solidBg?: boolean; controlHeight?: number; labelStyleGroupHeadings?: boolean; menuWidth?: string | number; scrollableMenu?: boolean } = {}): StylesConfig<any, false> {
  return {
    container: (base) => ({
      ...base,
      userSelect: 'none',
      WebkitUserSelect: 'none',
    }),
    control: (base, _state) => ({
      ...base,
      display: 'flex',
      alignItems: 'center',
      background: solidBg ? 'var(--bg-panel)' : 'transparent',
      border: 'none',
      boxShadow: 'none',
      minHeight: controlHeight,
      height: controlHeight,
      borderRadius: 6,
      fontSize: 11,
      cursor: 'pointer',
      transition: 'background 0.15s ease',
      '&:hover': { background: 'var(--bg-hover)' },
    }),
    valueContainer:      (base) => ({ ...base, height: controlHeight, padding: '0 8px', flexWrap: 'nowrap', display: 'flex', alignItems: 'center' }),
    indicatorsContainer: (base) => ({ ...base, height: controlHeight }),
    singleValue:         (base) => ({ ...base, color: 'var(--text-primary)',   fontSize: 11, margin: 0, lineHeight: 1 }),
    placeholder:         (base) => ({ ...base, color: 'var(--text-secondary)', fontSize: 11, margin: 0, lineHeight: 1 }),
    input:               (base) => ({ ...base, color: 'var(--text-primary)',   fontSize: 11, margin: 0, padding: 0, lineHeight: 1 }),
    indicatorSeparator:  ()    => ({ display: 'none' }),
    dropdownIndicator: (base, state) => ({
      ...base,
      padding: '0 6px',
      color: state.isFocused || state.selectProps.menuIsOpen ? 'var(--text-primary)' : 'var(--text-secondary)',
      transform: state.selectProps.menuIsOpen ? 'rotate(180deg)' : 'rotate(0deg)',
      transition: 'transform 0.2s ease, color 0.15s ease',
      '&:hover': { color: 'var(--text-primary)' },
    }),
    clearIndicator: (base) => ({ ...base, padding: '0 4px', color: 'var(--text-secondary)', '&:hover': { color: '#e10600' } }),
    menu: (base, state) => ({
      ...base,
      width: menuWidth ?? base.width,
      background: 'var(--bg-menu)',
      border: '1px solid var(--border)',
      borderRadius: 6,
      boxShadow: '0 8px 32px rgba(0,0,0,0.6)',
      zIndex: 9999,
      marginTop: 4,
      overflow: 'hidden',
      userSelect: 'none',
      WebkitUserSelect: 'none',
      transformOrigin: state.placement === 'top' ? 'bottom center' : 'top center',
      animation: `${state.placement === 'top' ? 'selectMenuEnterTop' : 'selectMenuEnterBottom'} ${SELECT_MENU_ANIMATION_MS}ms cubic-bezier(0.2, 0, 0, 1) both`,
      willChange: 'clip-path',
    }),
    menuPortal: (base) => ({ ...base, zIndex: 9999 }),
    menuList: (base) => ({
      ...base,
      padding: 4,
      ...(scrollableMenu ? {} : { maxHeight: 'none', overflowY: 'visible' as const }),
    }),
    group: (base) => labelStyleGroupHeadings ? ({
      ...base,
      paddingTop: 2,
      paddingBottom: 2,
    }) : base,
    groupHeading: (base) => labelStyleGroupHeadings ? ({
      ...base,
      color: 'var(--text-secondary)',
      fontSize: 9,
      fontWeight: 400,
      letterSpacing: '0.1em',
      textTransform: 'uppercase',
      margin: 0,
      padding: '2px 8px',
    }) : base,
    option: (base, state) => ({
      ...base,
      background: state.isSelected ? 'var(--border-focus)' : state.isFocused ? (isDark ? 'rgba(255,255,255,0.12)' : 'var(--bg-hover)') : 'transparent',
      color: state.isSelected ? '#fff' : 'var(--text-primary)',
      fontSize: 11,
      borderRadius: 4,
      padding: '5px 8px',
      cursor: 'pointer',
      transition: 'background 0.1s',
      '&:active': { background: 'var(--border-focus)', color: '#fff' },
    }),
  }
}
